# (problems for future me) if the function arguments written on multi line the program will not detect them
# the program will detect pointer to function as function

# inculding a space after int in "int " is curcial to differentiate between the variable type and just a string
returnTypes = ["u8 ", "void ","int ","float ","double ","bool ","char "]

def doxygenAs_html(input_csv_FilePath,output_html_FilePath):
    
    with open(input_csv_FilePath,"r") as file:
        with open(output_html_FilePath,"w") as html:
            html.write("""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Documentation</title>
        <!-- Include CSS styles for better presentation -->
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                padding: 20px;
            }
            h1, h2, h3 {
                color: #333;
            }
            code {
                font-family: Consolas, monospace;
                background-color: #f4f4f4;
                padding: 2px 6px;
                border-radius: 4px;
            }
            .content {
                max-width: 800px;
                margin: 0 auto;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <h1>Project Documentation</h1>
            <p>Welcome to the documentation for the project. Here you will find detailed information about each function.</p>
            """)
            for line in file.readlines():
                code = line.split(",")
                functionName = code[0]
                returnType = code[1]
                args = code[2:]
                
                html.write(f"""
    <h3>Function Name: <code>{functionName}</code></h3>
    <ul>
        <li>Return type: <code>{returnType}</code></li>
        <li>Arguments: 
                """)
                for arg in args:
                    html.write(f"<code>{arg}</code> ")
                html.write("""
        </li>
    </ul>      
                """)
            
            html.write("""

            <footer>
                <hr>
                <p>Generated by Ahmed Mahmoud Doxygen.</p>
            </footer>
        </div>
    </body>
    </html>
            """)

def doxygen(input_C_FilePath, output_csv_FilePath = "data.csv",generate_html_File = True, output_html_FilePath = "data.html"):
    
    # string.find() -> return a -1 value if the value not found
    notFound = -1
    try: 
        with open(input_C_FilePath,"r") as file:
            with open(output_csv_FilePath,"w") as dataFile:
            # looping on lines
                for line in file.readlines():
                    # looping on different return types
                    for returnType in returnTypes:
                        returnTypePosition = line.find(returnType)
                        if returnTypePosition != notFound: 
                            openBracketPosition = line.find("(")
                            if openBracketPosition != notFound:
                                #this if to differentiate between a function and if condtion
                                if openBracketPosition > returnTypePosition:
                                    functionName = line[returnTypePosition + len(returnType):openBracketPosition]
                                    closeBracketPosition = line.find(")")
                                    args = line[openBracketPosition + 1:closeBracketPosition]
                                    dataFile.write(f"{functionName},{returnType},{args}\n")
        if generate_html_File:
            doxygenAs_html(output_csv_FilePath, output_html_FilePath)
    except:
        print("Given file path doesn't exist")


doxygen("DIO_program.c")
